#!/usr/bin/env python3
"""
Pine Script Exporter for BTC IFVG Strategy
==========================================

Exports optimized parameters to TradingView Pine Script v5.

Features:
- Converts Python strategy to Pine Script
- Includes all IFVG + VP + EMAs rules
- Confluence scoring system
- Optimized parameters from Bayesian/Efficient Frontier
- Risk management (SL/TP, position sizing)

Usage:
    python pine_exporter.py --params=results/optimization/best_params.json
    python pine_exporter.py --atr=1.5 --vol=1.2 --ema_fast=18 --ema_slow=48
"""

import sys
import json
import argparse
from pathlib import Path
from datetime import datetime
from typing import Dict, Any

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

class PineScriptExporter:
    """Exports BTC trading strategy to Pine Script v5"""

    def __init__(self):
        self.script_template = self._get_script_template()

    def _get_script_template(self) -> str:
        """Get the base Pine Script template"""

        return '''//@version=5
indicator("BTC IFVG + Volume Profile + EMAs Strategy", overlay=true, timeframe="", timeframe_gaps=true)

// =============================================================================
// BTC IFVG + VOLUME PROFILE + EMAS STRATEGY - PINE SCRIPT v5
// =============================================================================
// Generated by BTC Trading IA System
// Generated: {timestamp}
// Parameters optimized for: {symbol}
// Optimization method: {opt_method}
// Best score: {best_score}
// =============================================================================

// =============================================================================
// INPUT PARAMETERS
// =============================================================================

// IFVG Parameters
atrLength = input.int(14, "ATR Length", minval=5, maxval=50)
atrMultiplier = input.float({atr_multi}, "ATR Multiplier", minval=0.1, maxval=3.0, step=0.1)

// Volume Profile Parameters
vpRows = input.int({vp_rows}, "VP Rows", minval=50, maxval=200)
vaPercent = input.float({va_percent}, "VA Percent", minval=0.6, maxval=0.8, step=0.01)
sdThresh = input.float({sd_thresh}, "SD Threshold", minval=0.1, maxval=0.3, step=0.01)

// EMA Parameters
emaFast5m = input.int({ema_fast_5m}, "EMA Fast 5m", minval=5, maxval=50)
emaSlow5m = input.int({ema_slow_5m}, "EMA Slow 5m", minval=20, maxval=100)
emaFast15m = input.int({ema_fast_15m}, "EMA Fast 15m", minval=5, maxval=50)
emaSlow15m = input.int({ema_slow_15m}, "EMA Slow 15m", minval=20, maxval=100)
emaFast1h = input.int({ema_fast_1h}, "EMA Fast 1h", minval=20, maxval=150)
emaSlow1h = input.int({ema_slow_1h}, "EMA Slow 1h", minval=50, maxval=300)

// Volume & Risk Parameters
volThresh = input.float({vol_thresh}, "Volume Threshold", minval=0.5, maxval=2.0, step=0.1)
minConfidence = input.float({min_confidence}, "Min Confidence", minval=0.1, maxval=1.0, step=0.1)
tpRR = input.float({tp_rr}, "Take Profit RR", minval=1.0, maxval=5.0, step=0.1)

// =============================================================================
// INDICATOR CALCULATIONS
// =============================================================================

// ATR for IFVG
atr = ta.atr(atrLength)

// IFVG Calculation (simplified for Pine)
highPrev = ta.valuewhen(ta.barstate.islast, high[1], 0)
lowPrev = ta.valuewhen(ta.barstate.islast, low[1], 0)
closePrev = ta.valuewhen(ta.barstate.islast, close[1], 0)

gapUp = close > highPrev and low > highPrev
gapDown = close < lowPrev and high < lowPrev

ifvgBull = gapUp and close > closePrev
ifvgBear = gapDown and close < closePrev

// Volume Profile (simplified - POC from recent bars)
vpLength = input.int(50, "VP Lookback", minval=20, maxval=200)
vpHigh = ta.highest(high, vpLength)
vpLow = ta.lowest(low, vpLength)
pocPrice = (vpHigh + vpLow) / 2  // Simplified POC

// EMAs
emaFast = ta.ema(close, emaFast5m)
emaSlow = ta.ema(close, emaSlow5m)

// Higher timeframe EMAs (simplified)
emaFastHTF = ta.ema(close, emaFast15m)
emaSlowHTF = ta.ema(close, emaSlow15m)

// Trend filter (1H EMA)
emaTrend = ta.ema(close, emaSlow1h)

// Volume conditions
volSMA = ta.sma(volume, 21)
volCondition = volume > volThresh * volSMA

// =============================================================================
// SIGNAL GENERATION
// =============================================================================

// Trend filter (close > EMA200_1h)
trendUp = close > emaTrend

// Momentum (EMA20_5m > EMA50_15m)
momentumUp = emaFast > emaFastHTF

// Confluence scoring
bullScore = 0.0
bullScore += ifvgBull ? 2.0 : 0.0
bullScore += close > pocPrice ? 1.0 : 0.0
bullScore += momentumUp ? 1.0 : 0.0
bullScore += volCondition ? 1.0 : 0.0
bullScore += trendUp ? 1.0 : 0.0

bearScore = 0.0
bearScore += ifvgBear ? 2.0 : 0.0
bearScore += close < pocPrice ? 1.0 : 0.0
bearScore += not momentumUp ? 1.0 : 0.0
bearScore += volCondition ? 1.0 : 0.0
bearScore += not trendUp ? 1.0 : 0.0

// Entry signals
bullSignal = bullScore >= 4.0 and trendUp
bearSignal = bearScore >= 4.0 and not trendUp

// =============================================================================
// PLOTTING
// =============================================================================

// Plot EMAs
plot(emaFast, color=color.blue, title="EMA Fast", linewidth=1)
plot(emaSlow, color=color.red, title="EMA Slow", linewidth=1)
plot(emaTrend, color=color.purple, title="Trend EMA", linewidth=2)

// Plot IFVG
plotshape(ifvgBull, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small, title="IFVG Bull")
plotshape(ifvgBear, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.small, title="IFVG Bear")

// Plot Volume Profile
plot(pocPrice, color=color.orange, title="POC", linewidth=2, style=plot.style_linebr)

// Plot signals
plotshape(bullSignal, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.large, title="Bull Signal")
plotshape(bearSignal, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.large, title="Bear Signal")

// Plot confluence scores
plot(bullScore, color=color.green, title="Bull Score", style=plot.style_histogram, linewidth=2)
plot(bearScore, color=color.red, title="Bear Score", style=plot.style_histogram, linewidth=2)

// =============================================================================
// ALERTS
// =============================================================================

alertcondition(bullSignal, title="Bull Signal Alert", message="BTC Bull Signal - Score: {{bullScore}}")
alertcondition(bearSignal, title="Bear Signal Alert", message="BTC Bear Signal - Score: {{bearScore}}")

// =============================================================================
// STRATEGY (for backtesting in Pine)
// =============================================================================

if strategy.position_size == 0
    if bullSignal
        strategy.entry("Long", strategy.long)
    else if bearSignal
        strategy.entry("Short", strategy.short)

// Risk management
stopLoss = strategy.position_avg_price * (1 - atrMultiplier * atr / strategy.position_avg_price)
takeProfit = strategy.position_avg_price * (1 + tpRR * atrMultiplier * atr / strategy.position_avg_price)

strategy.exit("Exit Long", "Long", stop=stopLoss, limit=takeProfit)
strategy.exit("Exit Short", "Short", stop=stopLoss, limit=takeProfit)

// =============================================================================
// STATISTICS
// =============================================================================

// Display confluence scores
plotchar(true, "Bull Score", tostring(bullScore), location=location.top, color=color.green, textcolor=color.white)
plotchar(true, "Bear Score", tostring(bearScore), location=location.top, color=color.red, textcolor=color.white)

// Display current ATR
plotchar(true, "ATR", tostring(atr), location=location.top, color=color.blue, textcolor=color.white)
'''

    def load_params_from_file(self, params_file: str) -> Dict[str, Any]:
        """Load optimized parameters from JSON file"""

        try:
            with open(params_file, 'r') as f:
                data = json.load(f)

            # Extract best_params
            if 'best_params' in data:
                params = data['best_params']
            else:
                params = data

            # Add metadata
            metadata = {
                'symbol': data.get('symbol', 'BTCUSD'),
                'opt_method': data.get('target_metric', 'unknown'),
                'best_score': data.get('best_score', 0),
                'timestamp': data.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
            }

            return {**params, **metadata}

        except Exception as e:
            print(f"❌ Error loading params from {params_file}: {e}")
            return {}

    def create_pine_script(self, params: Dict[str, Any]) -> str:
        """Create Pine Script from parameters"""

        # Default parameters
        defaults = {
            'atr_multi': 1.5,
            'va_percent': 0.7,
            'vp_rows': 120,
            'sd_thresh': 0.12,
            'ema_fast_5m': 18,
            'ema_slow_5m': 48,
            'ema_fast_15m': 18,
            'ema_slow_15m': 48,
            'ema_fast_1h': 95,
            'ema_slow_1h': 200,
            'vol_thresh': 1.2,
            'min_confidence': 0.6,
            'tp_rr': 2.2,
            'symbol': 'BTCUSD',
            'opt_method': 'manual',
            'best_score': 0,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }

        # Merge with provided params
        config = {**defaults, **params}

        # Format script
        script = self.script_template.format(**config)

        return script

    def save_pine_script(self, script: str, output_file: str):
        """Save Pine Script to file"""

        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(script)

            print(f"✅ Pine Script saved to: {output_file}")

        except Exception as e:
            print(f"❌ Error saving Pine Script: {e}")

    def export_from_params_file(self, params_file: str, output_file: str = None):
        """Export Pine Script from parameters file"""

        print(f"📊 Loading parameters from: {params_file}")

        params = self.load_params_from_file(params_file)

        if not params:
            return False

        print("📈 Parameters loaded:")
        for key, value in params.items():
            if not key.startswith(('symbol', 'opt_method', 'timestamp')):
                print(f"   {key}: {value}")

        script = self.create_pine_script(params)

        if output_file is None:
            # Generate output filename
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_file = f"scripts_pine/btc_strategy_{timestamp}.pine"

        # Create output directory
        Path(output_file).parent.mkdir(exist_ok=True)

        self.save_pine_script(script, output_file)

        return True

    def export_from_cli_params(self, **kwargs):
        """Export Pine Script from command line parameters"""

        print("📊 Using CLI parameters:")

        # Convert CLI params to dict
        params = {}
        param_mapping = {
            'atr': 'atr_multi',
            'vol': 'vol_thresh',
            'ema_fast': 'ema_fast_5m',
            'ema_slow': 'ema_slow_5m',
            'ema_fast_15m': 'ema_fast_15m',
            'ema_slow_15m': 'ema_slow_15m',
            'ema_fast_1h': 'ema_fast_1h',
            'ema_slow_1h': 'ema_slow_1h',
            'vp_rows': 'vp_rows',
            'va_percent': 'va_percent',
            'tp_rr': 'tp_rr'
        }

        for cli_key, script_key in param_mapping.items():
            if cli_key in kwargs and kwargs[cli_key] is not None:
                params[script_key] = kwargs[cli_key]
                print(f"   {script_key}: {kwargs[cli_key]}")

        script = self.create_pine_script(params)

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        output_file = f"scripts_pine/btc_strategy_cli_{timestamp}.pine"

        Path(output_file).parent.mkdir(exist_ok=True)
        self.save_pine_script(script, output_file)

        return True

def main():
    """Main CLI interface"""

    parser = argparse.ArgumentParser(
        description='Pine Script Exporter for BTC IFVG Strategy',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Export from optimized parameters file
  python pine_exporter.py --params=results/optimization/best_params.json

  # Export with custom parameters
  python pine_exporter.py --atr=1.5 --vol=1.2 --ema_fast=18 --ema_slow=48

  # Export to specific file
  python pine_exporter.py --params=best.json --output=my_strategy.pine
        """
    )

    parser.add_argument(
        '--params',
        help='Path to optimized parameters JSON file'
    )

    parser.add_argument(
        '--output', '-o',
        help='Output Pine Script file path'
    )

    # Parameter arguments
    parser.add_argument('--atr', type=float, help='ATR multiplier')
    parser.add_argument('--vol', type=float, help='Volume threshold')
    parser.add_argument('--ema_fast', type=int, help='EMA fast (5m)')
    parser.add_argument('--ema_slow', type=int, help='EMA slow (5m)')
    parser.add_argument('--ema_fast_15m', type=int, help='EMA fast (15m)')
    parser.add_argument('--ema_slow_15m', type=int, help='EMA slow (15m)')
    parser.add_argument('--ema_fast_1h', type=int, help='EMA fast (1h)')
    parser.add_argument('--ema_slow_1h', type=int, help='EMA slow (1h)')
    parser.add_argument('--vp_rows', type=int, help='Volume profile rows')
    parser.add_argument('--va_percent', type=float, help='Value area percent')
    parser.add_argument('--tp_rr', type=float, help='Take profit risk-reward')

    args = parser.parse_args()

    exporter = PineScriptExporter()

    if args.params:
        # Export from parameters file
        success = exporter.export_from_params_file(args.params, args.output)

    elif any([args.atr, args.vol, args.ema_fast, args.ema_slow]):
        # Export from CLI parameters
        cli_params = vars(args)
        success = exporter.export_from_cli_params(**cli_params)

    else:
        print("❌ Please provide either --params file or individual parameters")
        parser.print_help()
        return 1

    if success:
        print("✅ Pine Script export completed successfully!")
        return 0
    else:
        print("❌ Pine Script export failed!")
        return 1

if __name__ == '__main__':
    sys.exit(main())